# Generated by Django 5.2.9 on 2025-12-15 21:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('site_code', models.CharField(db_index=True, max_length=10)),
                ('site_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.sitetype')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('centerpoint', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('states', models.ManyToManyField(to='park.state')),
            ],
        ),
    ]
