# Generated by Django 5.2.9 on 2025-12-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='site_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='site_type',
        ),
        migrations.AddField(
            model_name='park',
            name='site_code',
            field=models.CharField(db_index=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.sitetype'),
        ),
    ]
