# Generated by Django 5.2.9 on 2025-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_remove_state_site_code_remove_state_site_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='site_type',
        ),
        migrations.AddField(
            model_name='park',
            name='site_types',
            field=models.ManyToManyField(to='park.sitetype'),
        ),
    ]
