# Generated by Django 5.2.9 on 2025-12-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_remove_park_site_type_park_site_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='website',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
