# Generated by Django 5.2.9 on 2025-12-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_park_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='box_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
