# Generated by Django 6.0 on 2026-02-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_park_box_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='parent_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sites', to='park.park'),
        ),
    ]
