# Generated by Django 6.0.3 on 2026-04-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_park_parent_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOIFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('FLM', 'Film'), ('MON', 'Monuments, statues, and other markers'), ('EXH', 'Interior / exterior exhibits'), ('SGN', 'Signs and waysides'), ('PUB', 'Publications'), ('NOT', 'NothingToReport'), ('OTH', 'Other')], max_length=4)),
                ('recommendation', models.CharField(blank=True, max_length=4)),
                ('description', models.TextField(blank=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park')),
            ],
        ),
    ]
