# Generated by Django 6.0.3 on 2026-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_doiflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doiflag',
            name='flag_type',
            field=models.CharField(choices=[('FLM', 'Film'), ('MON', 'Monuments, statues, and other markers'), ('EXH', 'Interior / exterior exhibits'), ('SGN', 'Signs and waysides'), ('PUB', 'Publications'), ('NOT', 'Nothing to report'), ('OTH', 'Other')], max_length=4),
        ),
    ]
