# Generated by Django 6.0.3 on 2026-09-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_alter_doiflag_flag_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('collection_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='park',
            name='parent_site',
        ),
        migrations.AddField(
            model_name='park',
            name='collections',
            field=models.ManyToManyField(to='park.parkcollection'),
        ),
        migrations.CreateModel(
            name='SubSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('subsite_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park')),
            ],
        ),
    ]
