# Generated by Django 5.2.9 on 2025-12-15 21:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
import sos_database.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('park', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalNotesCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAdditionalNotesCorrection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('additional_notes', models.TextField(null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical additional notes correction',
                'verbose_name_plural': 'historical additional notes corrections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTitleCorrection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical title correction',
                'verbose_name_plural': 'historical title corrections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.park')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('IN', 'In Scope'), ('OUT', 'Out of Scope'), ('DUP', 'Exact Duplicate')], db_index=True, max_length=4)),
                ('status', models.CharField(choices=[('LV', 'Live'), ('AP', 'Approved, Not Yet Live'), ('RD', 'Ready for Review'), ('AT', 'Needs Attention'), ('SV', 'Save for Later')], db_index=True, max_length=4)),
                ('box_id', models.CharField(db_index=True, max_length=255)),
                ('box_filename', models.CharField(max_length=255)),
                ('box_foldername', models.CharField(max_length=255)),
                ('photo_file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('date_taken', models.DateField(null=True)),
                ('title', models.TextField(null=True)),
                ('title_final', models.TextField(null=True)),
                ('additional_notes', models.TextField(null=True)),
                ('additional_notes_final', models.TextField(null=True)),
                ('main_image_url', models.ImageField(null=True, storage=sos_database.storage_backends.PublicMediaStorage(), upload_to='')),
                ('thumb_url', models.ImageField(null=True, storage=sos_database.storage_backends.PublicMediaStorage(), upload_to='')),
                ('location_orig', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('location_modified', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('location_type', models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.park')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.sign')),
            ],
        ),
    ]
