# Generated by Django 5.2.9 on 2025-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
