# Generated by Django 5.2.9 on 2025-12-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_sign_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='box_foldername',
        ),
    ]
