# Generated by Django 6.0 on 2025-12-19 22:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import sos_database.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photo_box_foldername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='additional_notes_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_modified',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_orig',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='photo',
            name='main_image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=sos_database.storage_backends.PrivateMediaStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.sign'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_url',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=sos_database.storage_backends.PrivateMediaStorage(), upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
