# Generated by Django 6.0 on 2026-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photo_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dt_form',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='dt_imported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
