# Generated by Django 6.0 on 2026-02-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_dt_form_photo_dt_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalnotescorrection',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photo'),
        ),
        migrations.AddField(
            model_name='historicaladditionalnotescorrection',
            name='photo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='photo.photo'),
        ),
        migrations.AddField(
            model_name='historicaltitlecorrection',
            name='photo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='photo.photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='bool_manual_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='titlecorrection',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photo'),
        ),
    ]
