# Generated by Django 6.0 on 2026-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_additionalnotescorrection_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalnotescorrection',
            name='photo_file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladditionalnotescorrection',
            name='photo_file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltitlecorrection',
            name='photo_file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titlecorrection',
            name='photo_file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='scope',
            field=models.CharField(blank=True, choices=[('IN', 'In Scope'), ('OUT', 'Out of Scope'), ('DUP', 'Exact Duplicate')], db_index=True, max_length=4),
        ),
    ]
