# Generated by Django 6.0 on 2026-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_additionalnotescorrection_photo_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalnotescorrection',
            name='photo_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladditionalnotescorrection',
            name='photo_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltitlecorrection',
            name='photo_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlecorrection',
            name='photo_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
