# Generated by Django 6.0 on 2026-02-16 20:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_alter_additionalnotescorrection_photo_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaladditionalnotescorrection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladditionalnotescorrection',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='historicaltitlecorrection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltitlecorrection',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='titlecorrection',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes (original)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title (original)'),
        ),
        migrations.CreateModel(
            name='HistoricalManualCorrection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo_file_name', models.CharField(max_length=255, null=True)),
                ('title', models.TextField(null=True)),
                ('additional_notes', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_type', models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='photo.photo')),
            ],
            options={
                'verbose_name': 'historical manual correction',
                'verbose_name_plural': 'historical manual corrections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_name', models.CharField(max_length=255, null=True)),
                ('title', models.TextField(null=True)),
                ('additional_notes', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_type', models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalNotesCorrection',
        ),
        migrations.DeleteModel(
            name='HistoricalAdditionalNotesCorrection',
        ),
        migrations.DeleteModel(
            name='HistoricalTitleCorrection',
        ),
        migrations.DeleteModel(
            name='TitleCorrection',
        ),
    ]
