# Generated by Django 6.0 on 2026-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_remove_historicaladditionalnotescorrection_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualcorrection',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmanualcorrection',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
