# Generated by Django 6.0 on 2026-02-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_historicalmanualcorrection_additional_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='location_orig',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='location_modified',
            new_name='location_final',
        ),
    ]
