# Generated by Django 6.0 on 2026-02-16 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_rename_location_orig_photo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location_type_final',
            field=models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location (original)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_type',
            field=models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3, verbose_name='Location type (original)'),
        ),
    ]
