# Generated by Django 6.0 on 2026-02-17 20:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_photo_location_type_final_alter_photo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanualcorrection',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dt_form',
            field=models.DateTimeField(null=True, verbose_name='Date submitted'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_final',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location (current)'),
        ),
    ]
