# Generated by Django 6.0 on 2026-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_historicalmanualcorrection_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualcorrection',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmanualcorrection',
            name='location_type',
            field=models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='location_type',
            field=models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3, null=True),
        ),
    ]
