# Generated by Django 6.0 on 2026-02-26 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_alter_historicalmanualcorrection_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanualcorrection',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='manualcorrection',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='photo',
            name='location_embedded',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location (Embedded in photo)'),
        ),
    ]
