# Generated by Django 6.0 on 2026-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_remove_historicalmanualcorrection_location_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('bool_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='box_filename',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('NML', 'Normal'), ('ALT', 'Altered'), ('ART', 'Artistic'), ('OTH', 'Other')], db_index=True, default='NML', max_length=4),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_type',
            field=models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3, verbose_name='Location type'),
        ),
        migrations.AddField(
            model_name='photo',
            name='collections',
            field=models.ManyToManyField(to='photo.collection'),
        ),
    ]
