# Generated by Django 6.0 on 2026-02-28 16:11

import django.db.models.deletion
import simple_history.models
import sos_database.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_collection_remove_photo_box_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRevisedPhoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo_file_name', models.CharField(max_length=255, null=True)),
                ('main_image_url', models.TextField(blank=True, max_length=255, null=True)),
                ('thumb_url', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='photo.photo')),
            ],
            options={
                'verbose_name': 'historical revised photo',
                'verbose_name_plural': 'historical revised photos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RevisedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_name', models.CharField(max_length=255, null=True)),
                ('main_image_url', models.ImageField(blank=True, max_length=255, null=True, storage=sos_database.storage_backends.PrivateMediaStorage(), upload_to='images')),
                ('thumb_url', models.ImageField(blank=True, max_length=255, null=True, storage=sos_database.storage_backends.PrivateMediaStorage(), upload_to='thumbs')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photo')),
            ],
        ),
    ]
