# Generated by Django 6.0 on 2026-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_historicalrevisedphoto_revisedphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='collections',
            field=models.ManyToManyField(null=True, to='photo.collection'),
        ),
    ]
