# Generated by Django 6.0 on 2026-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0018_alter_photo_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='photo',
            name='review_reason',
            field=models.CharField(blank=True, choices=[('SCP', 'Not sure if in scope'), ('BOD', 'Person or identifiable body part'), ('RFL', 'Reflection'), ('IMG', 'Poor image quality')], db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='collections',
            field=models.ManyToManyField(blank=True, to='photo.collection'),
        ),
    ]
