# Generated by Django 6.0.3 on 2026-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0019_alter_sign_options_photo_review_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(blank=True, choices=[('LV', 'Live'), ('AP', 'Approved, Not Yet Live'), ('RD', 'Ready for Review'), ('AT', 'Needs Attention'), ('SV', 'Save for Later')], db_index=True, max_length=4, null=True),
        ),
    ]
