# Generated by Django 6.0.3 on 2026-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0020_alter_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bool_exif_location',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(blank=True, choices=[('LV', 'Live'), ('AP', 'Approved, Not Yet Live'), ('RD', 'Ready for Review'), ('AT', 'Needs Attention'), ('SV', 'Save for Later'), ('RJ', 'Rejected')], db_index=True, max_length=4, null=True),
        ),
    ]
