# Generated by Django 6.0.3 on 2026-07-20 16:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_alter_doiflag_flag_type'),
        ('photo', '0021_photo_bool_exif_location_alter_photo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualcorrection',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Internal comment'),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Internal comment'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='review_reason',
            field=models.CharField(blank=True, choices=[('SCP', 'Not sure if in scope'), ('BOD', 'Person or identifiable body part'), ('PER', 'Personally identifying information'), ('RFL', 'Reflection'), ('IMG', 'Poor image quality'), ('ROT', 'Image needs to be rotated')], db_index=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPhoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scope', models.CharField(blank=True, choices=[('IN', 'In Scope'), ('OUT', 'Out of Scope'), ('DUP', 'Exact Duplicate')], db_index=True, max_length=4)),
                ('status', models.CharField(blank=True, choices=[('LV', 'Live'), ('AP', 'Approved, Not Yet Live'), ('RD', 'Ready for Review'), ('AT', 'Needs Attention'), ('SV', 'Save for Later'), ('RJ', 'Rejected')], db_index=True, max_length=4, null=True)),
                ('review_reason', models.CharField(blank=True, choices=[('SCP', 'Not sure if in scope'), ('BOD', 'Person or identifiable body part'), ('PER', 'Personally identifying information'), ('RFL', 'Reflection'), ('IMG', 'Poor image quality'), ('ROT', 'Image needs to be rotated')], db_index=True, max_length=4, null=True)),
                ('photo_type', models.CharField(choices=[('NML', 'Normal'), ('ALT', 'Altered'), ('ART', 'Artistic'), ('OTH', 'Other')], db_index=True, default='NML', max_length=4)),
                ('box_id', models.CharField(db_index=True, max_length=255)),
                ('photo_file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('date_taken', models.DateField(null=True)),
                ('dt_form', models.DateTimeField(null=True, verbose_name='Date submitted')),
                ('dt_imported', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title (original)')),
                ('title_final', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional notes (original)')),
                ('additional_notes_final', models.TextField(blank=True, null=True)),
                ('main_image_url', models.TextField(blank=True, max_length=255, null=True)),
                ('thumb_url', models.TextField(blank=True, max_length=255, null=True)),
                ('bool_exif_location', models.BooleanField(null=True)),
                ('location_embedded', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location (Embedded in photo)')),
                ('location_final', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location (current)')),
                ('location_type', models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3, verbose_name='Location type')),
                ('location_type_final', models.CharField(blank=True, choices=[('US', 'User-submitted'), ('PK', 'Park Centerpoint'), ('SOS', 'SOS corrected')], max_length=3)),
                ('bool_manual_correction', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='park.park')),
                ('sign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='photo.sign')),
            ],
            options={
                'verbose_name': 'historical photo',
                'verbose_name_plural': 'historical photos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
