# Generated by Django 6.0.3 on 2026-09-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_parkcollection_remove_park_parent_site_and_more'),
        ('photo', '0022_alter_historicalmanualcorrection_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalphoto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Photo model change log', 'verbose_name_plural': 'Photo model change log'},
        ),
        migrations.AddField(
            model_name='historicalphoto',
            name='subsite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='park.subsite'),
        ),
        migrations.AddField(
            model_name='photo',
            name='subsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.subsite'),
        ),
        migrations.AlterField(
            model_name='historicalphoto',
            name='photo_type',
            field=models.CharField(choices=[('NML', 'Regular'), ('ALT', 'Altered'), ('ART', 'Artistic'), ('OTH', 'Other')], db_index=True, default='NML', max_length=4),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('NML', 'Regular'), ('ALT', 'Altered'), ('ART', 'Artistic'), ('OTH', 'Other')], db_index=True, default='NML', max_length=4),
        ),
    ]
