name: Get Form Updates

on:
  # Define when the workflow should run (e.g., manual trigger)
  workflow_dispatch:

jobs:
  run_django_command:
    environment: get_form_update_env

    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgis/postgis:14-master
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: github_actions
    #     ports:
    #       - 5432:5432
    #     # needed because the postgres container does not provide a healthcheck
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If your manage.py is not in the root directory, adjust the path (e.g., cd src; pip install -r requirements.txt)

    - name: Move Box private key to file
      # Pass the secret as an environment variable to prevent it from
      # being exposed in the logs if it were used directly in the run command.
      env:
        BOX_KEY: ${{ secrets.BOX_KEY }}
      run: |
        echo "$BOX_KEY" > ./sos_database/sos_database/settings/box_cert.pem
      shell: bash

    # - name: Configure Django settings (Optional)
    #   run: |
    #     # Set environment variables required by your Django project (e.g., DJANGO_SETTINGS_MODULE)
    #     echo "DJANGO_SETTINGS_MODULE=your_project_name.settings" >> $GITHUB_ENV
    #   # Use secrets for sensitive data like database credentials
    #   env:
    #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #     # Add other necessary environment variables

    - name: Run the Django management command
      run: |
        # Navigate to directory containing manage.py if necessary (e.g., cd src)
        python manage.py check_form_updates
      # Ensure environment variables from the 'Configure Django settings' step are available
      env:
        # DJANGO_SETTINGS_MODULE: ${{ env.DJANGO_SETTINGS_MODULE }}
        # Pass other required env vars
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        BOX_JWT: ${{ secrets.BOX_JWT }}
        BOX_FORM_RESPONSES_FILE_ID: ${{ vars.BOX_FORM_RESPONSES_FILE_ID }}
        BOX_FORM_IMAGES_FOLDER_ID: ${{ vars.BOX_FORM_IMAGES_FOLDER_ID }}
